# Generated by Django 6.0.3 on 2026-08-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_followupactivity_client_followupactivity_deal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_terms',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='invoices/'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='service',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
