# Generated by Django 6.0.3 on 2026-08-29 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='custom_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
