"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path
import os
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'daphne',
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework_simplejwt.token_blacklist',
    'rest_framework',
    'companies',
    'accounts',
    'dashboard',
    'rest_framework_simplejwt',
    'django_extensions',
    'crm',
    'hr',
    'billing',
    'employees',
    'chat.apps.ChatConfig',
    'channels',
    'integrations'

]
ASGI_APPLICATION = "config.asgi.application"
CHANNEL_LAYERS = {

    "default": {

        "BACKEND": "channels.layers.InMemoryChannelLayer",

    },

}
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=24),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
}
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
}
POLAR_API_URL = "https://api.polar.sh"
POLAR_ACCESS_TOKEN = os.getenv("POLAR_ACCESS_TOKEN")
POLAR_PRODUCTS = {
    "Standard": {
        "monthly": "7dba7fca-6442-4561-8a22-ce46e30da744",
        "yearly": "00f5b5aa-b4c5-4997-afb9-e92cb3f69f5b",
    },
    "Premium": {
        "monthly": "a5889a95-9579-4610-bbf1-7cbce3339ab4",
        "yearly": "1a9c974f-2f8e-464c-b8a1-4da5a5ef43a3",
    },
    "Gold": {
        "monthly": "20b60b7e-ad08-48de-b836-50a14b401fc6",
        "yearly": "afa4e071-2c88-4d7a-a842-396d0167a02f",
    },
}
POLAR_SUCCESS_URL = "https://ridesai.cloud/payment-success"

POLAR_CANCEL_URL = "https://ridesai.cloud/checkout"


CORS_ALLOW_CREDENTIALS = True
SESSION_COOKIE_SAMESITE = "Lax"
AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'
MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

GOOGLE_CLIENT_ID = os.getenv("GOOGLE_CLIENT_ID")
GOOGLE_CLIENT_SECRET = os.getenv("GOOGLE_CLIENT_SECRET")
GOOGLE_REDIRECT_URI = os.getenv("GOOGLE_REDIRECT_URI")

SITE_URL = os.environ.get('SITE_URL', 'https://ridesai.cloud')

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("DB_NAME"),
        "USER": os.getenv("DB_USER"),
        "PASSWORD": os.getenv("DB_PASSWORD"),
        "HOST": os.getenv("DB_HOST"),
        "PORT": os.getenv("DB_PORT"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

CORS_ALLOW_ALL_ORIGINS = False
ALLOWED_HOSTS = [
    "ridesai.cloud",
    "www.ridesai.cloud",
    "187.127.217.78",
    "127.0.0.1"
]
CSRF_TRUSTED_ORIGINS = [
    "https://ridesai.cloud",
    "https://www.ridesai.cloud",
    "http://localhost:5173",
"http://127.0.0.1:8000",

]

CORS_ALLOWED_ORIGINS = [
    "https://ridesai.cloud",
    "https://www.ridesai.cloud",
    "http://localhost:5173",   # agar local testing bhi karni hai
    "http://127.0.0.1:8000"
]
ROTATE_REFRESH_TOKENS = True,
BLACKLIST_AFTER_ROTATION =  True,
JAZZMIN_SETTINGS = {
    "site_title": "Rides AI Admin",
    "site_header": "Rides AI",
    "site_brand": "Rides AI",
    "welcome_sign": "Welcome to Rides AI Management Portal",
    "copyright": "Rides Technologies",

    "show_ui_builder": True,

    "login_logo": "images/rides-logo.png",
    "site_logo": "images/rides-logo.png",

    "icons": {
        "accounts.User": "fas fa-users",
        "companies.Company": "fas fa-building",
        "billing.Plan": "fas fa-credit-card",
        "hr.Task": "fas fa-tasks",
        "chat.Conversation": "fas fa-robot",
    },

    "navigation_expanded": True,

    "hide_apps": [],

    "order_with_respect_to": [
        "companies",
        "accounts",
        "chat",
        "hr",
        "billing",
    ],
}