# Generated by Django 6.0.3 on 2026-08-28 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='tax_number',
        ),
        migrations.AddField(
            model_name='company',
            name='business_registration_document',
            field=models.FileField(blank=True, null=True, upload_to='company/business_registration/'),
        ),
        migrations.AddField(
            model_name='company',
            name='passport_size_photo',
            field=models.ImageField(blank=True, null=True, upload_to='company/owner/photo/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnic_back',
            field=models.ImageField(blank=True, null=True, upload_to='company/owner/cnic/back/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cnic_front',
            field=models.ImageField(blank=True, null=True, upload_to='company/owner/cnic/front/'),
        ),
    ]
